# Generated by Django 3.2 on 2021-04-29 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirpeaceScraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('passenger', models.CharField(max_length=50)),
                ('Bill', models.CharField(max_length=100)),
                ('paid_date', models.DateField(default=django.utils.timezone.now)),
                ('bank_name', models.CharField(max_length=500)),
                ('account_name', models.CharField(max_length=500)),
                ('account_number', models.CharField(max_length=500)),
                ('bank_code', models.CharField(max_length=500)),
                ('purpose', models.CharField(max_length=500)),
            ],
        ),
    ]
