# Generated by Django 3.1.6 on 2021-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerData1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('form_data', models.BinaryField(max_length=1000)),
                ('Scrape_Data', models.BinaryField(max_length=1000)),
            ],
        ),
    ]
